enum ReactionFlags{
    PLAYER_DID_MOVE = 'PLAYER_DID_MOVE',
    ENTITY_DID_MOVE = 'ENTITY_DID_MOVE',
    WAS_ATTACKED = 'WAS_ATTACKED',
    WAS_GRAPPLED = 'WAS_GRAPPLED',
    WAS_PULLED = 'WAS_PULLED',
    WAS_PUSHED = 'WAS_PUSHED',
    DID_DIE = 'DID_DIE',
  }

export default ReactionFlags;